### PR TITLE
set as UNEXPECTED_ACOUSTIC_CONNECTION status BACKOFF, NOISE and DEAF

### PR DESCRIPTION
**Pull request by joaobrittoneto**
@g-arjones, any comment here?

### CODE REVIEW

**Comment by joaobrittoneto** [comment]
[USBL UNEXPECTED_ACOUSTIC_CONNECTION: Improve driver](https://trello.com/c/LYEqQqDY/110-usbl-unexpectedacousticconnection-improve-driver)

**Comment by g-arjones** [comment]
Would you explain what are you trying to achieve with this change of behavior?

**Comment by joaobrittoneto** [comment]
Avoid worries for the user for acceptable and normal states in the acoustic connection.
Just let the user be aware of unexpected states by the driver.

**Comment by g-arjones** [comment]
Sounds reasonable.. 👍

**Comment by joaobrittoneto** [comment]
:+1: Merging

**Pull request merged**
