### PR TITLE
Make sure poth timeout_delivery_report and status_period are respected

### PR DESCRIPTION
**Pull request by joaobrittoneto**
Consider the smaller (diff of zero) to be the fd_timeout.

### CODE REVIEW

**Comment by g-arjones** [comment]
A very convoluted way to set a timeout IMO...

**Comment by doudou** [comment]
> A very convoluted way to set a timeout IMO...

@joaobrittoneto this actually does not completely help. Say I have a status period of 7s and a timeout of 8s, the earliest the component will be woken up to timeout the IM and send the next will be 14s ...

A simpler way would be to have a reasonable period at which the component is called no matter what. 500ms would sound like a good value to avoid overloading the CPU. This would be the granularity of the other two timeouts, which is fine for all intents and purposes w.r.t. the USBL.

**Comment by g-arjones** [comment]
> A simpler way would be to have a reasonable period at which the component is called no matter what. 500ms would sound like a good value to avoid overloading the CPU

When I discussed this with @joaobrittoneto, my suggestion was keeping the default iodrivers_base behavior (select() timeout = readTimeout) and keep it at 1s. What you are suggesting is also fine but requires us to refactor the updateHook() a bit otherwise we will be spamming the USBL with status request every 500ms.. IMO, we should keep all requests from the device to minimum since it seems that it some times fails to respond

**Comment by doudou** [comment]
> What you are suggesting is also fine but requires us to refactor the updateHook() a bit otherwise we will be spamming the USBL with status request every

Then ... what is `status_period` about ?

**Comment by g-arjones** [comment]
It's querying extended acoustic data status and other stuff from the device. As I understand it, that's just for debugging purposes (which is why I proposed setting it to 30s in another PR).

**Comment by g-arjones** [comment]
Thinking about it now, we probably shouldn't even ask for connection status unless there are pending data/IMs to be sent in the queue. updatehook() would do nothing in that case and the 500ms period would be fine. Thoughts?

**Comment by doudou** [comment]
> Thoughts?

Sounds like a good idea ..

**Comment by g-arjones** [comment]
Ok, I will do it...

**Comment by g-arjones** [comment]
Follow-up: #23

**Comment by joaobrittoneto** [comment]
I wonder if would not be also good to know the connection status when data/IM arrive from the acoustic channel?

**Comment by g-arjones** [comment]
> I wonder if would not be also good to know the connection status when data/IM arrive from the acoustic channel?

What for?

**Comment by joaobrittoneto** [comment]
Update counters, check for dropped burst data, maybe check the acoustic conditions that could explain it

**Comment by g-arjones** [comment]
The point is: do we NEED that every time data arrives? If we don't, I don't think we should poll it since we can't be sure the device will actually respond. @doudou opinion?

**Comment by joaobrittoneto** [comment]
Maybe respecting a period. 
I fear having a modem just receiving data, not sending, and one could not check the data counters, and acoustic status that could explain data drops in the component responsible to extract packets from the burst data

**Comment by joaobrittoneto** [comment]
Closing this one.

**Pull request closed without merging**
