### PR TITLE
Port_driven and fd_driven task

### PR DESCRIPTION
**Pull request by joaobrittoneto**
Define task as port_driven.

### CODE REVIEW

**Comment by joaobrittoneto** [comment]
The last commit makes also the Task fd_driven.
It does not go to timeout exception anymore. Ready to merge.

Just a remark, in case there is no data in the file descriptor or in the port to trigger the task, the updateHook is called every `io_read_timeout`period.

**Comment by doudou** [comment]
> The last commit makes also the Task fd_driven. It does not go to timeout exception anymore. Ready to merge.

OK, so if I get it right, what fixed your timeout is to call fd_driven after the port_driven ??????

**Comment by g-arjones** [comment]
?

Isin't the task supposed to be fd_driven OR port_driven? What am I missing?

**Comment by doudou** [comment]
> What am I missing?

It's supposed to be port_driven AND fd_driven

**Comment by joaobrittoneto** [comment]
>OK, so if I get it right, what fixed your timeout is to call fd_driven after the port_driven ??????

Yeah, I just copy and past the way it's done here https://github.com/rock-drivers/drivers-orogen-iodrivers_base/blob/master/iodrivers_base.orogen#L45, defining fd_driven after port_driven.

Looks like doing that way, the timeout doesn't calls the exception, but instead call the updateHook and reinitialize the time counter.

**Comment by joaobrittoneto** [comment]
The thing that doesn't feels right to me, is the `io_read_timeout` triggering the updateHook, what in practice turns the task periodic when there is no data (in port or in FD), but there is no documentation on that explain this behavior. 
In case the `io_read_tiemout` > `io_status_interval`, the last is completely irrelevant, once the `io_status` port (and other status ports as well) that should have a particular periodicity, is not respected.

**Comment by doudou** [comment]
`io_read_timeout` triggers a timeout because `iodrivers_base::Task` is setup to time out on that (https://github.com/rock-drivers/drivers-orogen-iodrivers_base/blob/master/tasks/Task.cpp#L70). One can override this in their `configureHook`. I won't comment on "it's not documented".

The reason for trigger can be checked with the underlying activity's `hasTimeout()` call, but this should NOT be needed.

This is why processIO exists as well, to ensure that whatever triggers the task the driver won't go into exception because of missing data. Note that it *is* important that a particular task does not require a certain triggering behaviour, as one changes triggers on various systems (e.g. changing to pure periodic is common)

**Comment by doudou** [comment]
> Looks like doing that way, the timeout doesn't calls the exception, but instead call the updateHook and reinitialize the time counter.

I'm going to have to verify what's really happening there ....

**Comment by doudou** [comment]
> > Looks like doing that way, the timeout doesn't calls the exception, but instead call the updateHook and reinitialize the time counter.

> I'm going to have to verify what's really happening there ....

In the meantime, feel free to merge.

**Comment by joaobrittoneto** [comment]
:+1:

**Pull request merged**
